# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://martisabate.github.io"
# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)
baseurl: /
# Google tracking id
google-tracking-id: "G-0RLHHTXXR9"
#############
# HTML Head #
#############
lang: "en"
author: "Martí Sabaté"
title: "{ Martí Sabaté }"
description: 
  "Hacking articles by Martí Sabaté"
keywords: "marti, sabate, personal, jekyll, theme, red team, hacking, pentesting, cybersecurity, malware analysis, exploit development, vulnerability assessment, network security, ethical hacking,
 information security, web application testing, intrusion detection, security architecture, blue team, cyber defense, phishing, social engineering, encryption, digital forensics, incident response
, SIEM, firewall, IDS, IPS, security policies, risk management, compliance, GDPR, cloud security, mobile security, IoT security, blockchain security, artificial intelligence in security, machine l
earning for security, penetration test tools, Metasploit, Burp Suite, OWASP, Kali Linux, cybersecurity trends, cybersecurity training, cyber law, privacy, data protection, VPN, zero trust, endpoin
t security, security operations center (SOC), cyber threat intelligence, hacking techniques, script kiddies, white hat, black hat, gray hat, security conference, CTF competitions, bug bounty, patc
h management, reverse engineering, cyber warfare, cyber espionage, secure coding, secure development lifecycle, security frameworks, ISO 27001, NIST, cybersecurity startups, cybersecurity innovati
on, cybersecurity awareness, phishing simulations, cybersecurity jobs, cybersecurity certifications, CISSP, CEH, OSCP, security audit, wireless security, database security, secure file transfer, r
ansomware, botnet, DDoS attacks, antivirus, sandboxing, threat modeling, security best practices, cyber insurance, quantum cryptography, secure messaging, identity and access management (IAM), bio
metric security, smart contract security, cyber resilience, security automation, DevSecOps, secure infrastructure, cybersecurity policy, ethical guidelines in cybersecurity, cybersecurity ethics, 
digital identity"
favicon: "/img/shield16.ico"
################
# Header layout #
################
black-favicon: "/img/shield32.ico"
background-img: "../img/cat-bg.png"
##############################
# Dynamic Text on the Header #
##############################
dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Thanks for visiting my cave"
  - text: "Everything is <span style='font-style: italic;'>Open-Source</span> as long as you can apply reverse engineering to it."
  - text: "In a sea of code, <em>I navigate the vulnerabilities.</em>"
  - text: "<code>while(true)</code> { <i>seek</i> vulnerabilities; <i>enhance</i> security; }"
# me-img: "/img/jetpacktocat.png"
# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/martisabate.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"
################
# Web app mode #
################
web-app-mode: True
# Icons for Web App mode
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"
########
# Blog #
########
post-preview-words: 20
paginate: 10
email-share: True
fb-share: False
twitter-share: False
linkedin-share: True
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False
disqus-shortname: "martisabate"
syntax-highlight: True
############
# Timeline #
############
events:
  - image: "/img/timeline/webhelpLogo.png"
    date: "November 2022 - April 2024"
    description: "[JOB] - L2 Technical Support Engineer externalized from Google assisting on Google Workspace products - Account Recovery and Security shard"
  - image: "/img/timeline/claranet.png"
    date: "January 2022 - November 2023"
    description: "[JOB] - L1 SOC IT Operation Support Agent"
  - image: "/img/timeline/fit.png"
    date: "September 2021 - January 2022"
    description: "[JOB] - Apprentice"
  - image: "/img/timeline/codelearn.jpeg"
    date: "May 2021 - September 2021"
    description: "[JOB] - Teaching programming to children and teenagers aged 5 to 18 as part of their extracurricular"
  - image: "/img/timeline/itb.jpg"
    date: "September 2020 - June 2022"
    description: "[HIGHER DEGREE] - COMPUTER SYSTEMS ADMINISTRATION AND NETWORKS, PROFESSIONAL PROFILE IN CYBERSECURIT"
# First image of the Timeline
timeline-img: "/img/timeline/marti.jpeg"
###########
# Contact #
###########
email: "msabp79@gmail.com"
# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False
################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: 
  "Thanks for reading my post ^^. This is Martí, from Barcelona. I like to contribute in cybersecurity projects, break things and rebuild them better than they were, just for security purposes."
author_blurb_image: "/img/marti.png"
##################
# Social Buttons #
##################
social:
  - title: "github"
    url: "https://github.com/MartiSabate"
  - title: "linkedin-in"
    url: "https://www.linkedin.com/in/mart%C3%AD-sabat%C3%A9-f%C3%A0bregas-729b31179/"
  - title: "rss"
    url: "https://martisabate.github.io/feed.xml"
############
# 404 page #
############
err-404-img: "/img/python404.png"
################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Blog: "latest-post"
  Timeline: "timeline"
  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
